# Generated by Django 5.0.6 on 2024-07-06 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post',
            new_name='userpost',
        ),
    ]
